# Collector specific configuration
metadata_url: "https://docs.google.com/spreadsheets/d/e/2PACX-1vS2JeGRKq-sORFvmPvl5OEnGXfHmdiefVd4cMFnJ_arOfFldSmm-xseVLZQpI8BKd6DCf7CZhmGub5Z/pub?gid=804807246&single=true&output=csv"
